spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mungnyangtoktok
    username: aza1200
    password: Umgee0723@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update