spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mungnyangtoktok
    username: aza1200
    password: Umgee0723@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false